### ISSUE TITLE
Preprocessing of FASTQ data prior to RepEnrich2 analysis

### ISSUE THREAD

**Issue by rauldiul** [nerettilab/RepEnrich2#18]
Dear @nskvir,

first of all, thank you for your great software. We are trying to use the software for the analysis of ChIP-seq data and we have a couple of questions regarding the preprocessing of the data prior to the analysis (we did not find much info on this issue reading the RepEnrich paper):

Is it recommended to do the usual preprocessing steps **prior to RepEnrich**, especially: 

- before alignment: read trimming/quality filtering
- after alignment: read deduplication for eliminating PCR duplicates

We ask because these steps are often performed in a standard Chip-seq analysis prior to peak calling, but we do not know if they would apply here in the RepEnrich pipeline.

thanks for your help

**Comment by nskvir** [comment]
Hi there, 

Thank you for your interest in Repenrich2!  With regard to your question, I would recommend adhering to the quality filtering and deduplication steps used in your standard Chip-seq analysis prior to peak calling, otherwise any potential PCR bias may be seen later in the distribution of counts.  

Best,
Nick
