### ISSUE TITLE
suggested bowtie2 parameters for RepEnrich2

### ISSUE THREAD

**Issue by akmorrow13** [nerettilab/RepEnrich2#20]
Hello,

This is a great tool! Thank you for maintaining this for the community.

I have a question about the suggested bowtie2 parameters that you recommend for using RepEnrich2. In the README, you suggest to use default bowtie2 and to not set ` -k` to allow multi-mapped reads. How does this work when aligning repetitive regions for use in RepEnrich2? Couldn't you be loosing some of the multi-alignments in these repetitive regions, or is there a good reason for only allowing unique alignment in bowtie2 for downstream analysis?

Thanks!

**Comment by nskvir** [comment]
Hi there,
Thanks for your interest in RepEnrich! In the case of the initial bowtie alignment, we're not really interested in all the specific locations that a multi-mapping read aligns to at first (since these are likely to be ambiguous), but rather whether or not it maps uniquely at all.  For those reads that are multi-mapping, a separate fasta file is generated, and a new alignment is run on a set of 'pseudo-genomes' for each element.  These pseudo-genomes consist of a set of concatenated sequences (with spacers in between) derived from each copy of the elements seen in the reference annotation from Repeatmasker used for the initial setup. Then, counts are assigned fractionally based on however many different elements the multi-mappers aligned to during these subsequent runs.  

I hope that clarifies things a bit!

**Comment by akmorrow13** [comment]
This makes sense, thank you. If you are using repenrich2 on RNA-seq, and therefore using the STAR aligner, would you recommend any parameters besides default?

**Comment by nskvir** [comment]
MAPQ value is used in our case to determine whether to call a read as 'uniquely' or 'multimapping'. Because every aligner assigns MAPQ scores differently, you'll want to check what value STAR uses (I think it is 255 for unique mappers, but I could be mistaken). You'll want to change the corresponding argument when running the Repenrich2_subset.py script, but other than that I think you should be fine.
