### ISSUE TITLE
Simple, low-complexity repeats and blacklisted region filtering

### ISSUE THREAD

**Issue by sirjuanjo** [nerettilab/RepEnrich2#22]
Hi @nskvir,

I am analyzing chip-seq data with your great software and I have two doubts:

- In your github tutorial, you selectively remove simple and low-complexity repeats from the analysis. Why do you do this, is it just to speed up the analysis or are there any other reasons?
- Additionally, I'm not sure about filtering or not chip-seq [blacklisted regions](https://www.nature.com/articles/s41598-019-45839-z). It is standard practice to filter them in "normal" chip-seq pipelines, and I usually do so to the aligned BAM. Nonetheless, these regions may involve some repetitive regions. Do you have any experience with filtering them prior to using RepEnrich2 or what would be your recommendation?

thanks for your help!

**Comment by nskvir** [comment]
Hi @sirjuanjo 
Thanks for using our software - I am not the original author, however I believe the simple and low-complexity repeats were removed deliberately and not just for the sake of saving time;  my guess would be that due to their properties (short length, very high AT or GC content) there are likely to be some technical issues with including them as a set of pseudo-genome assemblies.  

As far as filtering blacklisted regions in chip-seq data, I haven't run much of this type of data, but I believe that this is normally done to ensure high accuracy for the peak-calling. If you're more concerned with quantifying enrichment of repetitive regions, you may be able to skip the filtering, as the counts for any multimapping reads will be distributed across all of the elements to which they map.

I hope this helps!

Best,
Nick
